# Logging
wandb_log: true
wandb_project: 'daisy-wee'
wandb_run_name: '420m-instruct'
# Torch config
torch.coordinate_descent_tuning: false
# Pretraining checkpoint path
init_checkpoint: "checkpoints/20251106T2345-val2.710-step019074-run1-final.pt"
# Instruct SFT training configuration
train_shards: "data/instruct_mix/instruct_train_*.bin"
target_tokens: 6055526400
cooldown_frac: 0.999
learning_rate_schedule: linear_decay
training_sequence_length: 65536        #  N * 1024; must be divisible by window_block_size
train_attention_window_len: 3456        # largest sliding attention window used during training; must be divisible by window_block_size
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.999]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: true
    params:
      - group: head_params
        lr: .00006928
      - group: embed_params
        lr: .003464
      - group: scalar_params
        lr: .0002598
  - type: Muon
    momentum: .95
    weight_decay: 0.0
    params:
      - group: hidden_matrix_params
        lr: .0004
full_windows: true
# Gradient accumulation
grad_acc_steps: 1 # assumes world_size=8
# Evaluations
val_shards:
  - type: "instruct-mix"
    path: "data/instruct_mix/instruct_val_*.bin"
  - type: "fineweb-edu"
    path: "data/fineweb-edu/edu_fineweb_val_000000.bin"
val_loss_every_tokens:     26214400
val_seq_len: 262144       # 4 * 64 * 1024
tot_val_tokens: 10485760
# Checkpoints
checkpoint_warmup_tokens:     162201600     # token warmup before checkpoints
checkpoint_per_n_tokens:     1         # checkpoint interval by tokens
save_checkpoint: true
# Model Definition
model_spec: daisy_420m