# overfit test config, attempts overfit on 100000000 tokens. ~= few seconds (train), 30 seconds (device setup/compile)
# config assumes 8xh100; for different CUDA devices/counts try adjusting token volumes/grad_acc_steps proportionally
wandb_log: true
wandb_project: 'daisy-wee'
wandb_run_name: 'pico_tied_overfit'
# Torch config
torch.coordinate_descent_tuning: false
# Pretraining configuration
train_shards: "data/overfit/edu_fineweb_overfit_1M.bin" #attempting overfit on 100000000 tokens
target_tokens: 10_485_760  # = 20 steps, 10 epochs; note: 4*20*model_params = 2.4B tokens
cooldown_frac: 0.6
learning_rate_schedule: cosine_decay
training_sequence_length: 65536        #  N * 1024; must be divisible by window_block_size
train_attention_window_len: 1024        # largest sliding attention window used during training; must be divisible by window_block_size
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.8, 0.95]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: true
    params:
      - group: embed_params
        lr: 0.002
      - group: scalar_params
        lr: 0.015
  - type: Muon
    momentum: 0.95
    weight_decay: 0.0
    params:
      - group: hidden_matrix_params
        lr: 0.02
full_windows: false
# Gradient accumulation
grad_acc_steps: 1
# Evaluations
val_shards:
  - type: "fineweb-edu"
    path: "data/overfit/edu_fineweb_overfit_1M.bin"
# we don't care about val loss since we're overfitting on the training data
val_loss_every_tokens: 888_888_888_888
val_seq_len: 1
tot_val_tokens: 8  #must be divisible by global batch size
# Checkpoints
checkpoint_warmup_tokens:     1           # token warmup before checkpoints
checkpoint_per_n_tokens:      1           # checkpoint interval by tokens
save_checkpoint: false
# Model Definition
model_spec: daisy_pico_tied