# test config, attempts overfit on 100000000 tokens
wandb_log: true
wandb_project: 'daisy-wee'
wandb_run_name: 'pico_tied'
# Torch config
torch.coordinate_descent_tuning: true
# Pretraining configuration
train_shards: "data/overfit/edu_fineweb_overfit_1M.bin"
target_tokens: 200000000
cooldown_frac: 0.2
learning_rate_schedule: linear_decay
training_sequence_length: 4096        #  N * 1024; must be divisible by window_block_size
train_attention_window_len: 128        # largest sliding attention window used during training; must be divisible by window_block_size
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.8, 0.95]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: true
    params:
      - group: embed_params
        lr: 0.002
      - group: scalar_params
        lr: 0.0015

  - type: Muon
    momentum: 0.95
    weight_decay: 0.0
    params:
      - group: hidden_matrix_params
        lr: 0.02
full_windows: false
# Gradient accumulation
grad_acc_steps: 8
# Evaluations
val_shards:
  - type: "fineweb-edu"
    path: "data/overfit/edu_fineweb_overfit_1M.bin"
val_loss_every_tokens:     3276800
val_seq_len: 4096
tot_val_tokens: 4096
# Checkpoints
checkpoint_warmup_tokens: 0           # token warmup before checkpoints
checkpoint_per_n_tokens: 0            # checkpoint interval by tokens
save_checkpoint: true
# Model Definition
model_spec: daisy_pico_tied