# Logging
wandb_log: true
wandb_project: 'daisy-wee'
wandb_run_name: '450m'
# Torch config
torch.coordinate_descent_tuning: true
# Training
train_shards: "data/fineweb-edu/edu_fineweb_train_*.bin"
target_tokens: 35_000_000_000
cooldown_frac: 0.9
learning_rate_schedule: cosine_decay
training_sequence_length: 16384              #  N * 1024
train_attention_window_len: 3456          # largest sliding attention window used during training
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: true
    params:
      - group: head_params
        lr: 0.003464
      - group: embed_params
        lr: 0.1732
      - group: scalar_params
        lr: 0.01299
  - type: Muon
    momentum: 0.95
    weight_decay: 0.0
    params:
      - group: hidden_matrix_params
        lr: 0.025
full_windows: false
# Gradient accumulation
grad_acc_steps: 1
# Evaluations
val_shards:
  - type: "fineweb-edu"
    path: "data/fineweb-edu/edu_fineweb_val_*.bin"
val_loss_every_tokens: 52428800
val_seq_len: 65536              # N * 1024
tot_val_tokens: 10485760
# Checkpoints
checkpoint_warmup_tokens: 209715200               # token warmup before checkpoints
checkpoint_per_n_tokens: 52428800           # checkpoint interval by tokens
save_checkpoint: true
# Model Definition
model_spec: daisy_1p6b

