# Logging
wandb_log: true
wandb_project: 'daisy'
wandb_run_name: '420m'
# Torch config
torch.coordinate_descent_tuning: true
# Pretraining configuration
train_shards: "data/fineweb-edu/edu_fineweb_train_*.bin"
target_tokens: 10_000_000_000
cooldown_frac: 0.4
learning_rate_schedule: linear_decay
learning_rate_floor: 0.1
training_sequence_length: 65536        #  N * 1024; must be divisible by window_block_size
train_attention_window_len: 2304        # largest sliding attention window used during training; must be divisible by window_block_size
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: true
    params:
      - group: head_params
        lr: 0.003464
      - group: embed_params
        lr: 0.1732
      - group: scalar_params
        lr: 0.01299
  - type: Muon
    momentum: 0.95
    weight_decay: 0.0
    params:
      - group: hidden_matrix_params
        lr: 0.02
full_windows: false
# Gradient accumulation
grad_acc_steps: 1 # assumes world_size=8
# Evaluations
val_shards:
  - type: "fineweb-edu"
    path: "data/fineweb-edu/edu_fineweb_val_*.bin"
val_loss_every_tokens:    262144000 # 524288000 = 500 steps
val_seq_len: 262144       # 4 * 64 * 1024
tot_val_tokens: 10485760  # 5 steps
# Checkpoints
checkpoint_warmup_tokens:   209715200     # token warmup before checkpoints
checkpoint_per_n_tokens:     1         # checkpoint interval by tokens
save_checkpoint: true
# Model Definition
model_spec: daisy_420m