# Logging
wandb_log: true
wandb_project: 'daisy-650m'
wandb_run_name: '650m-task'
# SFT
train_mode: "sft"
# SFT data
sft_train_root: "data/instruct_tasks"
sft_train_split: "train"
sft_val_root: "data/instruct_tasks"   # optional
sft_val_split: "val"

# Run length: PER-RANK token budget
target_tokens: 12_000_000

# Hard max example length
train_attention_window_len: 3456
# Checkpoint
init_checkpoint: ""
# Torch config
torch.coordinate_descent_tuning: true

cooldown_frac: 0.999
learning_rate_floor: 0.1
learning_rate_schedule: linear_decay
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.999]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: true
    params:
      - group: head_params
        lr: 6.928e-5
      - group: embed_params
        lr: 3.464e-5
      - group: scalar_params
        lr: 2.598e-4
  - type: Muon
    momentum: .95
    weight_decay: 0.0
    params:
      - group: hidden_matrix_params
        lr: 0.0004
full_windows: true
# Gradient accumulation
grad_acc_steps: 1
# Evaluations
val_loss_every_tokens:    131072
# Checkpoints
checkpoint_warmup_tokens:   1     # token warmup before checkpoints
checkpoint_per_n_tokens:     1         # checkpoint interval by tokens
save_checkpoint: true
# Model Definition
model_spec: daisy_650m