# Logging
wandb_log: true
wandb_project: 'daisy-650m'
wandb_run_name: '650m-task'
# SFT
train_mode: "sft"
# SFT data
sft_train_root: "data/instruct_tasks"
sft_train_split: "train"
sft_global_batch_size: 27648      # global batch across all devices
sft_val_root: "data/instruct_tasks"
sft_val_split: "val"
# Checkpoint
init_checkpoint: "checkpoints/20251121T1729-val2.720-step011000-run1-best.pt"
# Torch config
torch.coordinate_descent_tuning: true
target_tokens: 12_000_000
cooldown_frac: 0.999
learning_rate_floor: 0.1
learning_rate_schedule: linear_decay
training_sequence_length: 3456        #  N * 1024; must be divisible by window_block_size
train_attention_window_len: 3456        # largest sliding attention window used during training; must be divisible by window_block_size
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.999]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: true
    params:
      - group: head_params
        lr: 6.928e-5
      - group: embed_params
        lr: 3.464e-5
      - group: scalar_params
        lr: 2.598e-4
  - type: Muon
    momentum: .95
    weight_decay: 0.0
    params:
      - group: hidden_matrix_params
        lr: 4e-4
full_windows: true
# Gradient accumulation
grad_acc_steps: 1
# Evaluations
val_loss_every_tokens:    26_214_400
val_seq_len: 65536
tot_val_tokens: 524_288
# Checkpoints
checkpoint_warmup_tokens:   1     # token warmup before checkpoints
checkpoint_per_n_tokens:     1         # checkpoint interval by tokens
save_checkpoint: true
# Model Definition
model_spec: daisy_650m